services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - 5454:5432
        volumes:
            - pg_data:/var/lib/postgresql/data
        env_file:
            - .env
    redis:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/root/redis
        env_file:
            - .env

    minio: 
        image: bitnami/minio:latest
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/minio
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

volumes:
    pg_data:
    redis_data:
    minio_data:
